services:
  redis:
    image: redis:7.4.1
    volumes:
      - data:/data
    command: redis-server --save 60 1 --loglevel warning
    ports:
      - "6379:6379"
  ollama:
    image: ollama/ollama:0.9.0
    environment:
      - OLLAMA_CONTEXT_LENGTH=4000
    volumes:
      - ollama_data:/root/.ollama
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
  core:
    build: ./core
    volumes:
      - ./core:/app
    env_file: .env
    depends_on:
      - redis
      
  # diffusion:
  #   build: ./diffusionservice
  #   volumes:
  #     - ./diffusionservice:/app
  #     - diffusers_data:/home/.cache/huggingface/hub
  #   ports:
  #     - "8000:8000"
  #   runtime: nvidia
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: all
  #             capabilities: [gpu]    
volumes:
  data:
  ollama_data:
  diffusers_data: