services:
  redis:
    image: redis:7.4.1
    volumes:
      - data:/data
    command: redis-server --save 60 1 --loglevel warning
    ports:
      - "6379:6379"
  discordchatbot:
    build: .
    volumes:
      - ./app:/app
    env_file: .env
    depends_on:
      - redis
volumes:
  data: