services:
  redis:
    image: redis:7.4.1
    volumes:
      - data:/data
    command: redis-server --save 60 1 --loglevel warning
    ports:
      - "6379:6379"
  ollama:
    image: ollama/ollama:0.7.0
    volumes:
      - ollama_data:/root/.ollama
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
  discordchatbot:
    build: .
    volumes:
      - ./app:/app
      - diffusers_data:/home/.cache/huggingface/hub
    env_file: .env
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]    
    depends_on:
      - redis
volumes:
  data:
  ollama_data:
  diffusers_data: