name: Build & Push application 
on:
  push:
    branches:
      - change-to-gcr.io
    paths:
      - .github/workflows/app-release.yaml
      - Dockerfile
      - app/**
jobs:
  build-push:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: dgowing95/discordchatbot:${{github.sha}}     