name: Create helm chart release
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}      

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Core docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/dgowing95/discordchatbot:core-${{github.ref_name}},ghcr.io/dgowing95/discordchatbot:core-latest
          context: ./core
          cache-from: type=registry,ref=ghcr.io/dgowing95/discordchatbot:core-latest
          cache-to: type=inline
  
  helm-chart-release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Add version to helm chart
        run: |
          sed -i -e 's/<<chart_version>>/${{github.ref_name}}/g' charts/dis-ai-bot/Chart.yaml

      - name: Add new image tag to chart values.yaml
        run: |
          sed -i -e 's/<<tag>>/${{github.ref_name}}/g' charts/dis-ai-bot/values.yaml

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
