name: Release
on:
  push:
    tags:
      - 'v*'

jobs:
  build_images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push Core docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/dgowing95/discordchatbot:core-${{github.ref_name}},ghcr.io/dgowing95/discordchatbot:core-latest
          context: ./core
          cache-from: type=registry,ref=ghcr.io/dgowing95/discordchatbot:core-latest
          cache-to: type=inline

  build_chart:
    needs: build_images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: azure/setup-helm@v4.3.0
      - name: Package Helm Chart
        run: |
          helm package charts/dis-ai-bot --version ${{ github.ref_name }} --app-version ${{ github.ref_name }}
      - uses: actions/upload-artifact@v4
        with:
          name: helm-dis-ai-bot-${{ github.ref_name }}
          path: dchatbot-${{ github.ref_name }}.tgz      

  create_release:
    needs: build_chart
    runs-on: ubuntu-latest
    permissions:
      contents: write    
    env:
      GH_TOKEN: ${{ github.token }}      
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/download-artifact@v4
        with:
          name: helm-dis-ai-bot-${{ github.ref_name }}
      - name: Create Release
        run: |
          gh release create ${{ github.ref_name }} \
            --title "Release ${{ github.ref_name }}" \
            --generate-notes

          gh release upload ${{ github.ref_name }} dchatbot-${{ github.ref_name }}.tgz