name: Run Tests
on:
  push:
    branches:
      - '*'
      - '!main'
jobs:
  run_pytest:
    defaults:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
   
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r core/requirements.txt
      
      - name: Run tests
        run: |
          PYTHONPATH=$(pwd) pytest core/tests/user_memory_tests.py