name: Verify Artifacts
on:
  push:
    branches:
      - '*'
      - '!main'

jobs:
  verify_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
   
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Core docker image
        uses: docker/build-push-action@v6
        with:
          tags: core-test
          context: ./core
          cache-from: type=registry,ref=ghcr.io/dgowing95/discordchatbot:core-latest
          cache-to: type=inline

  verify_chart::
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: azure/setup-helm@v4.3.0
      - name: Package Helm Chart
        run: |
          helm lint charts/dis-ai-bot